vim.g.mapleader = " "
vim.keymap.set("n", "<leader>pp", vim.cmd.Ex)
color = function()
	vim.cmd("hi LineNr guifg=white")
end
color()
vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")

vim.keymap.set("n", "J", "mzJ`z")
vim.keymap.set("n", "<C-d>", "<C-d>zz")
vim.keymap.set("n", "<C-u>", "<C-u>zz")
vim.keymap.set("n", "n", "nzzzv")
vim.keymap.set("n", "N", "Nzzzv")
-- greatest remap ever
vim.keymap.set("x", "<leader>p", [["_dP]])

vim.keymap.set("n", "<leader>zn", function()
	vim.cmd("ZenMode")
end)
vim.keymap.set("n", "<leader>cc", function()
	vim.cmd("hi LineNr guifg=white")
end)

-- next greatest remap ever : asbjornHaland
vim.keymap.set({ "n", "v" }, "<leader>y", [["+y]])
vim.keymap.set({ "n", "v" }, "<leader>p0", [["0p]])
vim.keymap.set({ "n", "v" }, "<leader>p1", [["1p]])
vim.keymap.set({ "n", "v" }, "<leader>p2", [["2p]])
vim.keymap.set({ "n", "v" }, "<leader>p3", [["3p]])
vim.keymap.set({ "n", "v" }, "<leader>p4", [["4p]])

vim.keymap.set("n", "<leader>Y", [["+Y]])

vim.keymap.set({ "n", "v" }, "<leader>d", [["_d]])

-- This is going to get me cancelled
vim.keymap.set("i", "<C-c>", "<Esc>")
vim.keymap.set("i", "jj", "<Esc>")
vim.keymap.set("i", "kk", "<Esc>")

vim.keymap.set("n", "Q", "<nop>")
vim.keymap.set("n", "<C-f>", "<cmd>silent !tmux neww tmux-sessionizer<CR>")
vim.keymap.set("n", "<leader>f", vim.lsp.buf.format)

vim.keymap.set("n", "yy", "Vy")
vim.keymap.set("n", "dd", "Vd")
vim.keymap.set("n", "cc", "Vc")
vim.keymap.set("n", "yaw", "vawy")
vim.keymap.set("n", "ya(", "va(y")
vim.keymap.set("n", "ya{", "va{y")
vim.keymap.set("n", "ya[", "va[y")
vim.keymap.set("n", "ya'", "va'y")
vim.keymap.set("n", 'ya"', 'va"y')
vim.keymap.set("n", "yiw", "viwy")
vim.keymap.set("n", "yiw", "viwy")
vim.keymap.set("n", "yi{", "vi{y")
vim.keymap.set("n", "yi(", "vi(y")
vim.keymap.set("n", "yi[", "vi[y")
vim.keymap.set("n", "yi'", "vi'y")
vim.keymap.set("n", 'yi"', 'vi"y')

vim.keymap.set("n", "daw", "vawd")
vim.keymap.set("n", "da{", "va{d")
vim.keymap.set("n", "da[", "va[d")
vim.keymap.set("n", "da(", "va(d")
vim.keymap.set("n", "da'", "va'd")
vim.keymap.set("n", 'da"', 'va"d')
vim.keymap.set("n", "diw", "viwd")
vim.keymap.set("n", "diw", "vawd")
vim.keymap.set("n", "di(", "vi(d")
vim.keymap.set("n", "di{", "va{d")
vim.keymap.set("n", "di[", "va[d")
vim.keymap.set("n", "di'", "va'd")
vim.keymap.set("n", 'di"', 'va"d')

vim.keymap.set("n", "ca{", "va{c")
vim.keymap.set("n", "caw", "vawc")
vim.keymap.set("n", "ca(", "va(c")
vim.keymap.set("n", "ca[", "va[c")
vim.keymap.set("n", "ca'", "va'c")
vim.keymap.set("n", 'ca"', 'va"c')
vim.keymap.set("n", "ciw", "viwc")
vim.keymap.set("n", "ciw", "vawc")
vim.keymap.set("n", "ci{", "va{c")
vim.keymap.set("n", "ci[", "va[c")
vim.keymap.set("n", "ci'", "va'c")
vim.keymap.set("n", 'ci"', 'va"c')

vim.keymap.set("n", "<C-k>", "<cmd>cnext<CR>zz")
vim.keymap.set("n", "<C-j>", "<cmd>cprev<CR>zz")
vim.keymap.set("n", "<leader>k", "<cmd>lnext<CR>zz")
vim.keymap.set("n", "<leader>j", "<cmd>lprev<CR>zz")
vim.keymap.set("n", "<leader>S", [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>]])
vim.keymap.set("n", "<leader>x", "<cmd>!chmod +x %<CR>", { silent = true })
vim.keymap.set("n", "<leader>s", vim.cmd.w, { silent = true })

vim.keymap.set("n", "<leader>vpp", "<cmd>e ~/.dotfiles/nvim/.config/nvim/lua/theprimeagen/packer.lua<CR>")
vim.keymap.set("n", "<leader>mr", "<cmd>CellularAutomaton make_it_rain<CR>")

vim.keymap.set("n", "<leader>es", function()
	vim.cmd("PackerSync")
end)

vim.keymap.set("n", "<leader><leader>", function()
	vim.cmd("so")
end)
